platform: linux

image_resource:
  type: registry-image
  source: 
    repository: "nexus.cardinalhealth.net:8445/anapsix/alpine-java"
    tag: latest

inputs:
  - name: project-source
  - name: temp-storage
  - name: nexus-security-tools-veracode
  
caches:
  - path: gradle
  - path: maven

outputs:
  - name: sonarqube-analysis-input
  - name: build-out
run:
  path: "project-source/concourse/ci/tasks/veracode.sh"

params:
  TERM: -dump
